### ISSUE TITLE
InvalidParameterError

### ISSUE THREAD

**Issue by marja-w** [MCFpy/mcf#4]
Hello,

first of all, I want to thank you for this package and its documentation.

However, I was not able to get the example to run on my data, which has 10 treatment arms. 

```
inpath = path_to_folder_of_csv_file  # the path where csv file lies
outpath = "./output_mcf"

indata = "modified_rct_preprocessed"  # the name of the csv file

d_name = [treatment]  # treatment column with 10 different treatment assignments
y_name = [outcome]  # outcome column a scale from 0 to 10
x_name_ord = variables  # list of column names for variables

mp_parallel = 8
mp_with_ray = False
modified_causal_forest(outpfad=outpath, datpfad=inpath, indata=indata, d_name=d_name, y_name=y_name,
                       x_name_ord=x_name_ord, mp_parallel=mp_parallel)
```

When I run the program I get following error:
```
Traceback (most recent call last):
  File "C:\Users\Marja\PyCharmProjects\causal-insufficiency\test_mcf.py", line 27, in <module>
    modified_causal_forest(outpfad=outpath, datpfad=inpath, indata=indata, d_name=d_name, y_name=y_name,
  File "C:\Users\Marja\.virtualenvs\causal-insufficiency\lib\site-packages\mcf\mcf_functions.py", line 176, in modified_causal_forest
    ) = modified_causal_forest_master(controls_dict, variable_dict,
  File "C:\Users\Marja\.virtualenvs\causal-insufficiency\lib\site-packages\mcf\mcf_functions.py", line 364, in modified_causal_forest_master
    old_y_name, new_y_name, lc_forest = mcf_lc.local_centering_cv(
  File "C:\Users\Marja\.virtualenvs\causal-insufficiency\lib\site-packages\mcf\mcf_loccent_functions.py", line 181, in local_centering_cv
    ) = gp_est.random_forest_scikit(
  File "C:\Users\Marja\.virtualenvs\causal-insufficiency\lib\site-packages\mcf\general_purpose_estimation.py", line 118, in random_forest_scikit
    regr.fit(x_train, y_1d)
  File "C:\Users\Marja\.virtualenvs\causal-insufficiency\lib\site-packages\sklearn\ensemble\_forest.py", line 340, in fit
    self._validate_params()
  File "C:\Users\Marja\.virtualenvs\causal-insufficiency\lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Marja\.virtualenvs\causal-insufficiency\lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'auto' (deprecated), 'sqrt', 'log2'} or None. Got 0 instead.
```

The console output runs until printing "Computing forests". 

Any help is appreciated. 

Thank you,
Marja

**Comment by hannahbus** [comment]
@marja-w, I suspect that the issue is related to package versioning. Feel free to mail (hannah.busshoff@unisg.ch) or share the versions you deploy, so I can also take a look (you can retrieve this information via ``conda list`` ).

**Comment by hbodory** [comment]
@marja-w, Thanks a lot for your feedback. We have meanwhile fixed the issue related to package versioning. In addition, we are now providing a requirements.txt file on the official mcf website on GitHub, which can be used for creating an environment with tested packages only. Please do not hesitate to contact us in case of further issues.
